apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool-deployment
  labels:
    app: multitool-app
spec:
  replicas: 2  # Начинаем с 1 реплики
  selector:
    matchLabels:
      app: multitool-app
  template:
    metadata:
      labels:
        app: multitool-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        # Простая проверка доступности
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 5
      
      - name: multitool
        image: wbitt/network-multitool:latest
        ports:
        - containerPort: 8080
        # Просто держим контейнер запущенным
        command: ["sleep"]
        args: ["infinity"]